//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class band
    {
        public int radif { get; set; }
        public int minutesnum { get; set; }
        public string matn { get; set; }
        public string subject { get; set; }
        public string result { get; set; }
        public string darmodrshakhs { get; set; }
    
        public virtual suratJalase suratJalase { get; set; }
    }
}
