//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class suratJalase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suratJalase()
        {
            this.bands = new HashSet<band>();
        }
    
        public int mnumber { get; set; }
        public int tnumber { get; set; }
        public Nullable<int> chandomin { get; set; }
        public System.DateTime date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<band> bands { get; set; }
        public virtual type type { get; set; }
    }
}
